In [99]:
from biopandas.pdb import PandasPdb
ppdb = PandasPdb().read_pdb('4ydl.pdb')
atom_df = ppdb.df['ATOM'].copy(deep=True)
atom_df.head()

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
0        ATOM            1                 N                  VAL           
1        ATOM            2                CA                  VAL           
2        ATOM            3                 C                  VAL           
3        ATOM            4                 O                  VAL           
4        ATOM            5                CB                  VAL           

  chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
0        G              44            ... -40.184   69.736  -48.615   
1        G              44            ... -39.749   70.530  -49.757   
2        G              44            ... -38.516   69.888  -50.392   
3        G              44            ... -37.727   69.228  -49.712   
4        G              44            ... -39.448   71.996  -49.341   

   occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
0        1.0     92.10                                  N    NaN         5  
1        1.0     87.67                                  C    NaN         6  
2        1.0     83.22                                  C    NaN         7  
3        1.0     84.92                                  O    NaN         8  
4        1.0     88.67                                  C    NaN         9  

[5 rows x 21 columns]

In [95]:
Heavy_chain = atom_df[atom_df['chain_id'] == 'B'] ## Heavy chain
Heavy_chain.drop_duplicates(['chain_id','residue_number']).head()

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
8704        ATOM         9945                 N                  VAL           
8711        ATOM         9952                 N                  ARG           
8722        ATOM         9963                 N                  LEU           
8730        ATOM         9971                 N                  VAL           
8737        ATOM         9978                 N                  GLN           

     chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
8704        B               2            ... -23.700   15.707  -43.752   
8711        B               3            ... -24.388   16.627  -47.020   
8722        B               4            ... -24.336   16.519  -50.553   
8730        B               5            ... -25.831   17.643  -53.389   
8737        B               6            ... -26.280   17.207  -56.690   

      occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
8704        1.0     34.70                                  N    NaN      9949  
8711        1.0     31.48                                  N    NaN      9956  
8722        1.0     28.74                                  N    NaN      9967  
8730        1.0     29.33                                  N    NaN      9975  
8737        1.0     29.85                                  N    NaN      9982  

[5 rows x 21 columns]

In [96]:
Light_chain = atom_df[atom_df['chain_id'] == 'C'] ## Light chain
Light_chain.drop_duplicates(['chain_id','residue_number']).head()

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
10398        ATOM        11902                 N                  GLU           
10407        ATOM        11911                 N                  ILE           
10415        ATOM        11919                 N                  VAL           
10422        ATOM        11926                 N                  LEU           
10430        ATOM        11934                 N                  THR           

      chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
10398        C               1            ...   4.705   15.307  -58.335   
10407        C               2            ...   2.485   12.912  -56.685   
10415        C               3            ...   2.660    9.538  -57.094   
10422        C               4            ...   0.413    6.946  -57.095   
10430        C               5            ...   0.100    3.531  -56.586   

       occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
10398        1.0     77.86                                  N    NaN     11906  
10407        1.0     58.73                                  N    NaN     11915  
10415        1.0     51.02                                  N    NaN     11923  
10422        1.0     46.83                                  N    NaN     11930  
10430        1.0     29.85                                  N    NaN     11938  

[5 rows x 21 columns]

In [97]:
Antigen_chain = atom_df[atom_df['chain_id'] == 'A'] ## Antigen chain
Antigen_chain.head()

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
2689        ATOM         3051                 N                  VAL           
2690        ATOM         3052                CA                  VAL           
2691        ATOM         3053                 C                  VAL           
2692        ATOM         3054                 O                  VAL           
2693        ATOM         3055                CB                  VAL           

     chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
2689        A              44            ...   7.375   23.552  -14.838   
2690        A              44            ...   6.699   22.582  -15.690   
2691        A              44            ...   5.459   23.206  -16.319   
2692        A              44            ...   4.615   23.774  -15.622   
2693        A              44            ...   6.299   21.315  -14.901   

      occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
2689        1.0     76.65                                  N    NaN      3055  
2690        1.0     72.92                                  C    NaN      3056  
2691        1.0     72.54                                  C    NaN      3057  
2692        1.0     73.28                                  O    NaN      3058  
2693        1.0     76.12                                  C    NaN      3059  

[5 rows x 21 columns]

In [98]:
Antigen_chain.drop_duplicates(['chain_id','residue_number']).head()

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
2689        ATOM         3051                 N                  VAL           
2696        ATOM         3058                 N                  TRP           
2710        ATOM         3072                 N                  LYS           
2719        ATOM         3081                 N                  ASP           
2727        ATOM         3089                 N                  ALA           

     chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
2689        A              44            ...   7.375   23.552  -14.838   
2696        A              45            ...   5.362   23.110  -17.641   
2710        A              46            ...   2.565   22.938  -19.989   
2719        A              47            ...   1.067   22.506  -23.261   
2727        A              48            ...  -1.734   24.521  -23.830   

      occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
2689        1.0     76.65                                  N    NaN      3055  
2696        1.0     66.66                                  N    NaN      3062  
2710        1.0     56.79                                  N    NaN      3076  
2719        1.0     51.12                                  N    NaN      3085  
2727        1.0     50.62                                  N    NaN      3093  

[5 rows x 21 columns]

In [85]:
A_coord = Antigen_chain[['x_coord','y_coord','z_coord']].to_numpy()
A_coord

array([[  7.375,  23.552, -14.838],
       [  6.699,  22.582, -15.69 ],
       [  5.459,  23.206, -16.319],
       ...,
       [  1.656,  20.226, -15.794],
       [  2.31 ,  19.517, -14.999],
       [  1.27 ,  19.825, -16.911]])

In [86]:
H_coord = Heavy_chain[['x_coord','y_coord','z_coord']].to_numpy()
H_coord

array([[-23.7  ,  15.707, -43.752],
       [-23.19 ,  16.399, -44.923],
       [-23.807,  15.785, -46.179],
       ...,
       [-41.175, -21.008, -94.295],
       [-40.798, -22.807, -92.182],
       [-39.956, -23.967, -91.076]])

In [79]:
diff = A_coord - H_coord
diff

array([30.565,  7.153, 30.085])

In [82]:
import numpy as np
## to get rid of negative distance
dist = abs(diff)
print(dist)

[30.565  7.153 30.085]


In [89]:
## Looping every residue from heavy chain overy every residue from antigen chain to calculate distance 

distance = []
for a in A_coord:
#     print(a)
    for h in H_coord:
        dis = a-h
        dist_ = abs(dis)
        distance.append(dist_)
    

In [91]:
len(distance)

4548390

In [93]:
distance[1:10]

[array([30.565,  7.153, 30.085]),
 array([31.182,  7.767, 31.341]),
 array([31.172,  8.986, 31.527]),
 array([29.029,  7.216, 30.139]),
 array([28.495,  6.635, 31.448]),
 array([28.441,  6.482, 28.936]),
 array([31.763,  6.925, 32.182]),
 array([32.358,  7.41 , 33.417]),
 array([32.044,  6.458, 34.561])]